version: '3.8'

services:
  pong1:
    build: .
    environment:
      - PORT=5001
      - PONG_MESSAGE=Pong1
    ports:
      - "5001:5001"

  pong2:
    build: .
    environment:
      - PORT=5002
      - PONG_MESSAGE=Pong2
    ports:
      - "5002:5002"